import { describe, expect, it } from 'vitest';
import { chooseAIMove } from '../game/ai';
import { createDeck, seededRandom, shuffleDeck } from '../game/deck';
import { applyMove, calculateFinalScores, createInitialGame, drawCard } from '../game/engine';
import { Card, EMPTY_STATS, GameState, MatchSettings, Player } from '../game/models';
import { captureForSelection, cardPoints, findAdditionGroups, findAdditionPairs, findCaptureOptions, findRankMatches, optionForSelection, playerPoints } from '../game/rules';

const settings: MatchSettings = { playerName: 'Tester', playerCount: 2, difficulty: 'hard', room: 'classic', turnSeconds: 20, sound: false, hints: false, reduceMotion: true };
const c = (rank: Card['rank'], id: string = rank, suit: Card['suit'] = 'spades'): Card => ({ id, rank, suit, value: rank === 'A' ? 1 : /^\d+$/.test(rank) ? Number(rank) : null });
const p = (id: string, captured: Card[] = []): Player => ({ id, name: id, isHuman: id === 'p1', captured, stats: EMPTY_STATS() });
const state = (center: Card[] = [], captured1: Card[] = [], captured2: Card[] = [], ring: Card[] = [c('2', 'ring-2')]): GameState => ({ ring, center, players: [p('p1', captured1), p('p2', captured2)], currentPlayerIndex: 0, firstPlayerIndex: 0, difficulty: 'hard', room: 'classic', turnSeconds: 20, sound: false, hints: false, reduceMotion: true, winnerIds: [], moveNumber: 0, turn: { phase: 'draw', captureOptions: [], message: '' } });

describe('deck and setup', () => {
  it('creates two 52-card decks and exactly two total Jokers', () => { const deck = createDeck(); expect(deck).toHaveLength(106); expect(deck.filter((card) => card.rank === 'JOKER')).toHaveLength(2); expect(new Set(deck.map((card) => card.id)).size).toBe(106); });
  it('shuffles without missing or duplicating cards', () => { const deck = createDeck(); const shuffled = shuffleDeck(deck, seededRandom(42)); expect(shuffled).not.toEqual(deck); expect(new Set(shuffled.map((card) => card.id))).toEqual(new Set(deck.map((card) => card.id))); });
  it('places four cards in the middle and 102 in the circle', () => { const game = createInitialGame(settings, 8); expect(game.center).toHaveLength(4); expect(game.ring).toHaveLength(102); expect(game.players).toHaveLength(2); });
  it('keeps the selected game room in the match', () => { expect(createInitialGame({ ...settings, room: 'rush' }, 8).room).toBe('rush'); });
  it('keeps the selected turn timer in the match', () => { expect(createInitialGame({ ...settings, turnSeconds: 30 }, 8).turnSeconds).toBe(30); });
});

describe('middle captures', () => {
  it('allows all same-rank Middle cards to be captured together', () => { const game = state([c('7', 'a'), c('7', 'b'), c('4')]); const options = findCaptureOptions(game, c('7', 'drawn')); expect(findRankMatches(c('7'), game.center)).toHaveLength(2); expect(options.some((option) => option.capturedCardIds.length === 2 && option.capturedCardIds.includes('a') && option.capturedCardIds.includes('b'))).toBe(true); });
  it('finds exactly two-card additions', () => { expect(findAdditionPairs(c('8'), [c('3'), c('5'), c('2')]).map((cards) => cards.map((card) => card.rank))).toContainEqual(['3', '5']); });
  it('allows three or more cards to add to the drawn value', () => { expect(findAdditionGroups(c('8'), [c('4', 'four'), c('3', 'three'), c('A', 'one')]).map((cards) => cards.map((card) => card.rank))).toContainEqual(['4', '3', 'A']); });
  it('counts Ace as one for addition', () => { expect(findAdditionPairs(c('7'), [c('A'), c('6')])).toHaveLength(1); });
  it('keeps face cards out of addition', () => { expect(findAdditionPairs(c('10'), [c('J'), c('Q'), c('K')])).toHaveLength(0); });
  it('resolves a selected capture without exposing hints', () => { const game = state([c('3', 'a'), c('5', 'b')]); const options = findCaptureOptions(game, c('8', 'drawn')); expect(optionForSelection(options, ['b', 'a'])?.groups[0].kind).toBe('add'); expect(optionForSelection(options, ['a'])).toBeUndefined(); });
  it('captures every selected card in a multi-card addition', () => { let game = state([c('4', 'four'), c('3', 'three'), c('A', 'one'), c('K', 'left')], [], [], [c('8', 'drawn-8'), c('2', 'remain')]); game = drawCard(game, 'drawn-8'); const option = captureForSelection(game, ['four', 'three', 'one']); expect(option?.label).toBe('4 + 3 + A'); game = applyMove(game, option ?? null); expect(game.players[0].captured.map((card) => card.id)).toEqual(['four', 'three', 'one', 'drawn-8']); expect(game.center.map((card) => card.id)).toEqual(['left']); });
  it('captures a match and several separate sums with one drawn card', () => { let game = state([c('9', 'nine'), c('8', 'eight'), c('A', 'one'), c('4', 'four'), c('5', 'five')], [], [], [c('9', 'drawn-9'), c('2', 'remain')]); game = drawCard(game, 'drawn-9'); const option = captureForSelection(game, ['nine', 'eight', 'one', 'four', 'five']); expect(option?.groups.map((group) => [...group.cardIds].sort()).sort()).toEqual([['eight', 'one'], ['five', 'four'], ['nine']].sort()); game = applyMove(game, option ?? null); expect(game.players[0].captured.map((card) => card.id)).toEqual(['nine', 'eight', 'one', 'four', 'five', 'drawn-9']); expect(game.center).toHaveLength(0); });
  it('allows a drawn card to match the top of the current player pile', () => { const game = state([], [c('4', 'pile-4')]); const option = optionForSelection(findCaptureOptions(game, c('4', 'drawn-4')), []); expect(option?.id).toBe('pile-match-4'); expect(option?.capturedCardIds).toEqual([]); });
  it('offers the full matching stack from the top of an opponent pile', () => { const game = state([], [], [c('6', 'locked-6'), c('4', 'top-4a'), c('4', 'top-4b')]); const option = findCaptureOptions(game, c('4', 'drawn')).find((item) => item.targetPlayerId === 'p2'); expect(option?.capturedCardIds).toEqual(['top-4a', 'top-4b']); });
  it('keeps deeper opponent cards locked when the visible top does not match', () => { const game = state([], [], [c('6', 'locked-6'), c('4', 'top-4')]); expect(findCaptureOptions(game, c('6', 'drawn')).some((option) => option.targetPlayerId)).toBe(false); });
});

describe('turn flow and final pick', () => {
  it('removes exactly one Circle card on every pick', () => { let game = state([], [], [], [c('2', 'pick'), c('3', 'stay-a'), c('4', 'stay-b')]); game = drawCard(game, 'pick'); expect(game.ring.map((card) => card.id)).toEqual(['stay-a', 'stay-b']); });
  it('continues after capture', () => { let game = state([c('2', 'middle-2')], [], [], [c('2', 'ring-2'), c('3', 'remain')]); game = drawCard(game, 'ring-2'); game = applyMove(game, game.turn.captureOptions[0].id); expect(game.currentPlayerIndex).toBe(0); expect(game.turn.phase).toBe('draw'); expect(game.players[0].stats.extraTurns).toBe(1); });
  it('adds a matching drawn card directly to the top pile and continues', () => { let game = state([], [c('4', 'pile-4')], [], [c('4', 'ring-4'), c('3', 'remain')]); game = drawCard(game, 'ring-4'); const option = optionForSelection(game.turn.captureOptions, []); game = applyMove(game, option?.id ?? null); expect(game.players[0].captured.map((card) => card.id)).toEqual(['pile-4', 'ring-4']); expect(game.currentPlayerIndex).toBe(0); expect(game.turn.phase).toBe('draw'); });
  it('takes a matching top stack from an opponent and continues', () => { let game = state([], [], [c('6', 'stays'), c('4', 'take-1'), c('4', 'take-2')], [c('4', 'ring-4'), c('3', 'remain')]); game = drawCard(game, 'ring-4'); const option = game.turn.captureOptions.find((item) => item.targetPlayerId === 'p2'); game = applyMove(game, option?.id ?? null); expect(game.players[0].captured.map((card) => card.id)).toEqual(['take-1', 'take-2', 'ring-4']); expect(game.players[1].captured.map((card) => card.id)).toEqual(['stays']); expect(game.currentPlayerIndex).toBe(0); expect(game.turn.phase).toBe('draw'); });
  it('allows a missed valid move with no take-back', () => { let game = state([c('2', 'middle-2')], [], [], [c('2', 'ring-2'), c('3', 'remain')]); game = drawCard(game, 'ring-2'); expect(game.turn.captureOptions.length).toBeGreaterThan(0); game = applyMove(game, null); expect(game.currentPlayerIndex).toBe(1); expect(game.center.map((card) => card.id)).toContain('ring-2'); });
  it('gives the middle to the final drawer', () => { let game = state([c('K', 'middle-k')]); game = drawCard(game, 'ring-2'); game = applyMove(game, null); expect(game.turn.phase).toBe('game-over'); expect(game.center).toHaveLength(0); expect(game.players[0].captured.map((card) => card.id)).toEqual(['middle-k', 'ring-2']); });
  it('gives leftovers after a final capture', () => { let game = state([c('2', 'match'), c('K', 'left')]); game = drawCard(game, 'ring-2'); game = applyMove(game, game.turn.captureOptions[0].id); expect(game.players[0].captured.map((card) => card.id)).toEqual(['match', 'ring-2', 'left']); });
});

describe('Jokers and scoring', () => {
  it('a Joker immediately sweeps opponent piles and the middle', () => { let game = state([c('4', 'middle')], [c('2', 'mine')], [c('K', 'theirs')], [c('JOKER', 'joker-red', 'joker'), c('3', 'remain')]); game = drawCard(game, 'joker-red'); expect(game.turn.phase).toBe('draw'); expect(game.players[1].captured).toHaveLength(0); expect(game.center).toHaveLength(0); expect(game.players[0].captured.map((card) => card.id)).toEqual(['mine', 'theirs', 'middle', 'joker-red']); expect(game.ring).toHaveLength(1); });
  it('a final Joker ends normally after its sweep', () => { let game = state([c('4', 'middle')], [], [c('Q', 'theirs')], [c('JOKER', 'joker-black', 'joker')]); game = drawCard(game, 'joker-black'); expect(game.turn.phase).toBe('game-over'); expect(game.players[0].captured).toHaveLength(3); });
  it('scores faces as twenty, numbers as five, and Jokers as thirty', () => { expect(['J', 'Q', 'K'].map((rank) => cardPoints(c(rank as Card['rank'])))).toEqual([20, 20, 20]); expect(playerPoints([c('A'), c('10'), c('JOKER', 'j', 'joker')])).toBe(40); });
  it('orders final scores by points, not card count', () => { const game = state([], [c('2'), c('3'), c('4')], [c('K')], []); expect(calculateFinalScores(game).map((score) => score.points)).toEqual([20, 15]); });
  it('shows the final card-count point breakdown', () => { const game = state([], [c('2'), c('A'), c('Q'), c('JOKER', 'joker', 'joker')], [], []); expect(calculateFinalScores(game)[0]).toMatchObject({ cards: 4, numberCards: 2, numberPoints: 10, faceCards: 1, facePoints: 20, jokers: 1, jokerPoints: 30, points: 60 }); });
  it('reports equal point totals as joint winners', () => { let game = state([c('4', 'middle')], [c('A', 'mine')], [c('2', 'their-2'), c('3', 'their-3'), c('5', 'their-5')], [c('6', 'last')]); game = drawCard(game, 'last'); game = applyMove(game, null); expect(game.winnerIds).toEqual(['p1', 'p2']); });
  it('AI returns only a legal capture or legal end-turn choice', () => { const game = state([c('3', 'a'), c('5', 'b')]); const drawn = c('8', 'drawn'); const ready = { ...game, turn: { phase: 'choose' as const, drawnCard: drawn, captureOptions: findCaptureOptions(game, drawn), message: '' } }; for (const difficulty of ['easy', 'medium', 'hard'] as const) { const choice = chooseAIMove(ready, difficulty, seededRandom(1)); expect(choice === null || ready.turn.captureOptions.some((option) => option.id === choice.id)).toBe(true); } });
});
